Repository googleapis/java-domains, pull requests merged in 2021-05, with the labels that each got.

#32 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: domains, automerge, cla: yes, context: none

#33 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: domains, automerge, cla: yes

#34 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: domains, cla: yes, context: full

#36 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: domains, automerge, cla: yes, context: full

#37 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: domains, automerge, cla: yes, context: full

#39 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: domains, automerge, cla: yes, context: full

#41 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: domains, automerge, cla: yes, context: full

#46 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: domains, automerge, cla: yes
